ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Architecture Constraints


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Any requirement that constraints software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)


.Further Information

See https://docs.arc42.org/section-2/[Architecture Constraints] in the arc42 documentation.

****
endif::arc42help[]
=== Technical constraints
|===
|Constraint|Explanation
|React|The use of React.js framefork for the frontend.
|Wikidata|It will be used to generate questions.
|===
=== Conventions
|===
|Constraint|Explanation
|Use of English|The documentation will be all written in English as it is the "software-related" language all over the world.
|Arch42|The documentation will follow the Arch42 template as a way to split and order all the information related with the software product.
|===
