ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope

ifdef::arc42help[]
[role="arc42help"]

.Contents
Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

Context diagrams

Lists of communication partners and their interfaces.

.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

endif::arc42help[]

=== Business Context

|===
| Communication Partner | Inputs | Outputs

| Cliente| Nombre de usuario, contraseña
| Puntuación del juego, preguntas obtenidas de Wikidata

| Base de Datos| Nombre de usuario, contraseña, puntuación de cada partida| Validación de credenciales, almacenamiento de puntuaciones

| Wikidata| Solicitud de información sobre la pregunta del juego
| Pregunta generada con información relevante

| ChatGPT| Pregunta del juego y respuesta correcta| Pistas para ayudar al usuario a responder mejor
|===  

"comit con la cuenta personal" 

=== Technical Context

ifdef::arc42help[]
[role="arc42help"]

.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decisions based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

endif::arc42help[]



<optionally: Explanation of technical interfaces>

<Mapping Input/Output to Channels>