ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope



=== Business Context

|===
| Communication Partner | Inputs | Outputs

| Cliente| Nombre de usuario, contraseña
| Puntuación del juego, preguntas obtenidas de Wikidata

| Base de Datos| Nombre de usuario, contraseña, puntuación de cada partida| Validación de credenciales, almacenamiento de puntuaciones

| Wikidata| Solicitud de información sobre la pregunta del juego
| Pregunta generada con información relevante

| ChatGPT| Pregunta del juego y respuesta correcta| Pistas para ayudar al usuario a responder mejor
|===

=== Technical Context

El desarrollo de la parte técnica aún está en proceso. Sin embargo, se han considerado las siguientes tecnologías:

Base de datos: MongoDB.

Comunicación con ChatGPT: SSH.

Interfaz de usuario: React.

BackEnd: Node.js.

A medida que se avance en el desarrollo, se definirán más detalles sobre los protocolos y canales de comunicación.



<optionally: Explanation of technical interfaces>

<Mapping Input/Output to Channels>