ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== Registro en la Aplicación
[plantuml, registration, png]
----
actor User
participant App
participant Gateway
participant UserService
database DBuser

User -> App: Selecciona opción de registro
User <-- App: Muestra pantalla de registro
User -> App: Ingresa datos de registro
App -> Gateway: Envía los datos
Gateway -> UserService: Envía los datos
UserService -> UserService: Comprueba los datos

alt usuario válido
    UserService -> DBuser: Guarda datos de registro
    UserService <-- DBuser: Confirma registro
    Gateway <-- UserService: Confirma registro
    App <-- Gateway: Confirma registro
    User <-- App: Confirma registro
else usuario no válido
    Gateway <-- UserService: Deniega registro
    App <-- Gateway: Deniega registro
    User <-- App: Deniega registro
end
----

=== Inicio de Sesión en la Aplicación
[plantuml, login, png]
----
actor User
participant App
participant Gateway
participant AuthService
database DBuser

User -> App: Ingresa credenciales
App -> Gateway: Envía los datos
Gateway -> AuthService: Envía los datos
AuthService -> DBuser: Comprueba los datos

alt usuario válido
    AuthService <-- DBuser: Confirma login
    Gateway <-- AuthService: Confirma login
    App <-- Gateway: Confirma login
    User <-- App: Confirma login
else usuario no válido
    AuthService <-- DBuser: Deniega login
    Gateway <-- AuthService: Deniega login
    App <-- Gateway: Deniega login
    User <-- App: Deniega login
end
----
=== Consulta del Ranking
[plantuml, ranking, png]
----
actor User
participant App
participant Gateway
participant RankingService
database DBranking

User -> App: Selecciona opción de ver el ranking
App -> Gateway: Pide el ranking
Gateway -> RankingService: Pide el ranking
RankingService -> DBranking: Pide todos los rankings
RankingService <-- DBranking: Devuelve todos los rankings
Gateway <-- RankingService: Devuelve todos los rankings
App <-- Gateway: Devuelve todos los rankings
User <-- App: Muestra el ranking
----
