ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== Registro en la Aplicación
[plantuml, registration, png]
----
actor User
participant App
participant Gateway
participant UserService
database DBuser

User -> App: Selecciona opción de registro
User <-- App: Muestra pantalla de registro
User -> App: Ingresa datos de registro
App -> Gateway: Envía los datos
Gateway -> UserService: Envía los datos
UserService -> UserService: Comprueba los datos

alt usuario válido
    UserService -> DBuser: Guarda datos de registro
    UserService <-- DBuser: Confirma registro
    Gateway <-- UserService: Confirma registro
    App <-- Gateway: Confirma registro
    User <-- App: Confirma registro
else usuario no válido
    Gateway <-- UserService: Deniega registro
    App <-- Gateway: Deniega registro
    User <-- App: Deniega registro
end
----

=== Inicio de Sesión en la Aplicación
[plantuml, login, png]
----
actor User
participant App
participant Gateway
participant AuthService
database DBuser

User -> App: Ingresa credenciales
App -> Gateway: Envía los datos
Gateway -> AuthService: Envía los datos
AuthService -> DBuser: Comprueba los datos

alt usuario válido
    AuthService <-- DBuser: Confirma login
    Gateway <-- AuthService: Confirma login
    App <-- Gateway: Confirma login
    User <-- App: Confirma login
else usuario no válido
    AuthService <-- DBuser: Deniega login
    Gateway <-- AuthService: Deniega login
    App <-- Gateway: Deniega login
    User <-- App: Deniega login
end
----

=== Generación de Preguntas
[plantuml, question_generation, png]
----
database DBquestions
participant CreateService
participant Gateway
participant QuestionGeneratorService
database DBquestiongenerator

loop cada 60 segundos
    CreateService -> DBquestions: Pide plantilla de pregunta
    CreateService <-- DBquestions: Devuelve plantilla de pregunta
    CreateService -> CreateService: Genera una pregunta
    Gateway <-- CreateService: Envía la pregunta generada
    Gateway -> QuestionGeneratorService: Envía la pregunta generada
    QuestionGeneratorService -> DBquestiongenerator: Guarda la pregunta generada
    alt más de 500 preguntas generadas
        DBquestiongenerator -> DBquestiongenerator: Borra la pregunta más antigua
    else pregunta existente
        DBquestiongenerator -> DBquestiongenerator: Actualiza la pregunta
    end
end
----

=== Respuesta a una Pregunta
[plantuml, question_response, png]
----
actor User
participant App
participant Gateway
participant GeneratedQuestionService
database DBquestions
participant QuestionGeneratorService
database DBquestiongenerator
participant RecordService
database DBrecords

User -> App: Pide una pregunta
App -> Gateway: Pide una pregunta
Gateway -> QuestionGeneratorService: Pide una pregunta
QuestionGeneratorService -> DBquestiongenerator: Pide una pregunta
QuestionGeneratorService <-- DBquestiongenerator: Devuelve una pregunta generada
Gateway <-- QuestionGeneratorService: Devuelve una pregunta generada
App <-- Gateway: Devuelve una pregunta generada
User <-- App: Muestra pregunta con opciones
Gateway -> GeneratedQuestionService: Envía la pregunta generada
GeneratedQuestionService -> DBquestions: Guarda la pregunta generada

alt tiempo no finalizado
    User -> App: Selecciona opción de respuesta
    App -> App: Verifica respuesta seleccionada
    alt respuesta correcta
        alt última pregunta
            User <-- App: Muestra mensaje de respuesta correcta y finaliza el juego
            App -> RecordService: Envía los datos de la partida
            RecordService -> DBrecords: Guarda los datos de la partida
            User <-- App: Muestra los datos de la partida
        else no última pregunta
            User <-- App: Muestra mensaje de respuesta correcta y continúa el juego
        end
    else respuesta incorrecta
        alt última pregunta
            User <-- App: Muestra mensaje de respuesta incorrecta y finaliza el juego
            App -> RecordService: Envía los datos de la partida
            RecordService -> DBrecords: Guarda los datos de la partida
            User <-- App: Muestra los datos de la partida
        else no última pregunta
            User <-- App: Muestra mensaje de respuesta incorrecta y continúa el juego
        end
    end
else tiempo finalizado
    App -> RecordService: Envía los datos de la partida
    RecordService -> DBrecords: Guarda los datos de la partida
    User <-- App: Muestra los datos de la partida
end
----