openapi: 3.0.0
info:
  title: User Service API
  description: API para gestionar usuarios, incluyendo la creación de nuevos usuarios.
  version: "1.0.0"
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://app.swaggerhub.com/apis/JavierEsquinas/usersapi/1.0.0'
  - description: Development server
    url: http://localhost:8001
paths:
  /adduser:
    post:
      summary: Crear un nuevo usuario.
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Nombre de usuario único.
                  example: "john_doe"
                password:
                  type: string
                  description: Contraseña del usuario.
                  example: "securepassword123"
      responses:
        '200':
          description: Usuario creado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID único del usuario.
                    example: "64a7b2f4e4b0c123456789ab"
                  username:
                    type: string
                    description: Nombre de usuario.
                    example: "john_doe"
                  password:
                    type: string
                    description: Contraseña encriptada del usuario.
                    example: "$2b$10$abcdefg1234567890hijklmnopqrstuvwxyz"
        '400':
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error.
                    example: "Username already exists"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error.
                    example: "Internal server error"

  /health:
    get:
      summary: Verificar el estado del servicio
      operationId: healthCheck
      responses:
        '200':
          description: Servicio funcionando correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"